### ISSUE TITLE
How to install the st7789 module?

### ISSUE THREAD

**Issue by JL-EU** [bdash9/T-picoC3-ESP32-RP2040#1]
Thanks for your demo on Youtube. 
One question: How do you install the st7789 module from russhughes?
I get the error: ImportError: no module named 'st7789'

If I use the package manger in Thonny this particular module is not available.

**Comment by bdash9** [comment]
HI,

You will need to create a tft_config.py<https://github.com/bdash9/LilyGo-T-PicoC3-hello/blob/main/tft_config.py> file and upload it to the RP2040

https://github.com/bdash9/LilyGo-T-PicoC3-hello/blob/main/tft_config.py


Hope this helps,
Ben

From: JL-EU ***@***.***>
Date: Wednesday, January 17, 2024 at 5:51 PM
To: bdash9/T-picoC3-ESP32-RP2040 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bdash9/T-picoC3-ESP32-RP2040] How to install the st7789 module? (Issue #1)

Thanks for your demo on Youtube.
One question: How do you install the st7789 module from russhughes?
I get the error: ImportError: no module named 'st7789'

If I use the package manger in Thonny this particular module is not available.

**Comment by JL-EU** [comment]
Thanks for your reply. I realised that I had to install the pre-compiled firmware: https://github.com/russhughes/st7789_mpy/tree/master/firmware/T-DISPLAY-RP2040
Now it works, thanks!
